### ISSUE TITLE
Coding: Develop Chat Section UI

### ISSUE THREAD

**Issue by NeoAnoman** [Sonal240/Sanganaka-Learning-App#6]
## Description
As a developer,
I need a  chat mock-up created,
so that I can add it as a component.

## Definition of Done
- [ ] Approval by 1 team member.

## Estimation
5-6 hours

Design link for reference:
https://xd.adobe.com/view/878cfb17-c975-48b2-a37e-ca4203ed7c29-d2df/

**Comment by Sonal240** [comment]
Kindly follow the issue template 🙃😅
